-- Ponto por QR Code (controle interno, NÃO é ponto oficial — Portaria 671)
-- Aplicada direto no banco em 24/09/2026 via conector Supabase do Claude.
-- Não precisa rodar de novo — este arquivo é só o registro do que foi feito.
--
-- ponto_locais: locais com QR Code (codigo aleatório vai no link do QR).
-- ponto_registros: marcações. Sem policy de insert/update/delete — só se
--   insere pela função registrar_ponto (horário do servidor, nome vindo do
--   token de login, confere GPS x posição do local, ignora toque duplo).
-- RLS: cada pessoa vê só os próprios registros; admin vê todos.
-- Locais criados: "Armário Almoxarifado" e "Recepção de Veículos".
--
-- (SQL completo aplicado: ver migração "ponto_qrcode" no painel do Supabase
--  > Database > Migrations.)
